# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: csv_pokemon_export_development
  # username: postgres   # Uncomment and specify if necessary
  # password: password   # Uncomment and specify if necessary
  # host: localhost      # Uncomment and specify if necessary
  # port: 5432           # Uncomment and specify if necessary

test:
  <<: *default
  database: csv_pokemon_export_test
  # username: postgres   # Uncomment and specify if necessary
  # password: password   # Uncomment and specify if necessary
  # host: localhost      # Uncomment and specify if necessary
  # port: 5432           # Uncomment and specify if necessary

production:
  <<: *default
  database: csv_pokemon_export_production
  username: <%= ENV["CSV_POKEMON_EXPORT_DATABASE_USERNAME"] %>
  password: <%= ENV["CSV_POKEMON_EXPORT_DATABASE_PASSWORD"] %>
  host: <%= ENV["CSV_POKEMON_EXPORT_DATABASE_HOST"] %>
  port: <%= ENV.fetch("CSV_POKEMON_EXPORT_DATABASE_PORT") { 5432 } %>
